name: stars_wars_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3+1
  http: ^0.13.5
  oxidized: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  mocktail: ^0.3.0-dev.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
